//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webNamana.BusinessLogic.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _202506152049175_TrainingMigration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _202506152049175_TrainingMigration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webNamana.BusinessLogic.Migrations.202506152049175_TrainingMigration", typeof(_202506152049175_TrainingMigration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAM1Y3W7bNhS+H9B3EHSdik6CAlsgt0jsZAgWJ0GV9p6WjhyiFKmSlGc/2y72SHuFHerXovwTp9lQ5CYmz/nO/8dj//PX3+GnVca9JSjNpBj7p8HI90DEMmFiMfYLk77/1f/08d0v4XWSrbyvjdy5lUNNocf+szH5BSE6foaM6iBjsZJapiaIZUZoIsnZaPQbOT0lgBA+Ynle+LkQhmVQfsCPEyliyE1B+UwmwHV9jjdRierd0wx0TmMY+3/CHD9RQYOrQjMBWt/JBYuD6VWp63uXnFF0KwKe+h4VQhpq0OmLLxoio6RYRDkeUP60zgHlUso11MFcdOIvjWt0ZuMinWIDFRfayOxIwNPzOlHEVX9Vuv02kZjKa0y5Wduoy3SO/SdFmcA6Vxe+55q8mHBlxTdzPkUBJoJShYEOGoygD3biuSonbfNgj9m/E29ScFMoGAsojKL8xHss5pzFf8D6SX4DMRYF55sRYAx41zvAo0clc1Bm/RnS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
