//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webNamana.BusinessLogic.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _202505031937381_InitialCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _202505031937381_InitialCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webNamana.BusinessLogic.Migrations.202505031937381_InitialCreate", typeof(_202505031937381_InitialCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAM1Y227jNhB9L9B/EPSclWwHC7SBvIvEjgujcRJEzr7T0tghSpEqSXntb+tDP6m/0KHuF9+TLoq8RNTMmZnDuVn//PW393UTMWsNUlHBh3bf6dkW8ECElK+GdqKXn36xv375+SfvPow21rdC7trIoSZXQ/tN6/jGdVXwBhFRTkQDKZRYaicQkUtC4Q56vV/dft8FhLARy7K8l4RrGkH6gI8jwQOIdULYTITAVH6Ob/wU1XokEaiYBDC0v8MCnwgnzl2iKAelHsSKBs74LtW1rVtGCbrlA1vaFuFcaKLR6ZtXBb6Wgq/8GA8Im29jQLklYQryYG4q8VPj6g1MXG6lWEAFidIiOhOwf50T5bbVL6LbLolEKu+Rcr01Uad0Du3X8WJOFgyDbxu7GTFpBOtsj1GAcidFoaAcpFM6BcSV1Ra8KpMFc8r8XVmjhOlEwpBDoiVhV9ZzsmA0+B22c/EH8CFPGKt7jD7ju8YBHj1LEYPU2xdY5nFM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
